### ISSUE TITLE
1주차 과제: Github 친해지기 

### ISSUE THREAD

**Issue by Livenow14** [Learning-Now/2021-Java-Study#1]
## 목표
깃허브에 익숙해지자

## 학습할 것 (필수)
- (public) 개인 레포지토리 만들기
- 깃 bash 명령어 공부하기  
- 레포지토리에 브랜치를 따서, 원격 저장소에 올리고, pullrequest 날리기 
- 개인 레포에 1주차 폴더 , **마크다운** 형식으로 공부한거 정리하기  
- 정리해야 할 것 ( 깃 bash 사용법, 마크다운 사용법, 브렌치 만드는법) 

## 마감
21년 1월 4일

## 준비
intelij 설치
[java jdk 1.8 download](https://www.oracle.com/kr/java/technologies/javase/javase-jdk8-downloads.html)

## 제출 양식 
url : **개인레포지토리 주소** (main 브렌치로 작업해주세요)

**Comment by BLINK-ONCE** [comment]
https://www.youtube.com/watch?v=GaKjTjwcKQo&t=261s

**Comment by jeongyuneo** [comment]
https://github.com/jeongyuneo/java-study

**Comment by jeongyuneo** [comment]
1주차 과제 완료
url : https://github.com/jeongyuneo/Java-study

**Comment by BLINK-ONCE** [comment]
1주차 과제
url: https://github.com/BLINK-ONCE/2021-java-study-HW

**Comment by dbswl067** [comment]
1주차 과제 완료
https://github.com/dbswl067/2021-java-a

**Comment by dustndus8** [comment]
1주차 과제
https://github.com/dustndus8/2021-Java-Study-1.git
