### ISSUE TITLE
3주차 과제: 자바 타입 이해하기

### ISSUE THREAD

**Issue by Livenow14** [Learning-Now/2021-Java-Study#15]
### **정리할 것**

- java code convetion

---

### **목표**

자바의 프리미티브 타입, 변수 그리고 배열을 사용하는 방법을 익힙니다.

### 정리할 것

- 프리미티브 타입 종류와 값의 범위 그리고 기본 값
- 프리미티브 타입과 레퍼런스 타입
- 리터럴
- 변수 선언 및 초기화하는 방법
- 변수의 스코프와 라이프타임
- 타입 변환, 캐스팅 그리고 타입 프로모션
- 1차 및 2차 배열 선언하기
- 타입 추론, var

## **제출 양식**

- pr 예시: **[2주차] 이니셜 제출**
- 이슈 예시:

```java
2주차 완료
url: ~~
```

**Comment by dustndus8** [comment]
3주차 완료
url: https://github.com/dustndus8/2021-Java-Study-1.git

**Comment by jeongyuneo** [comment]
3주차 완료
url: https://github.com/jeongyuneo/2021-Java-Study/tree/3주차

**Comment by BLINK-ONCE** [comment]
3주차 완료
url: https://github.com/BLINK-ONCE/2021-Java-Study/tree/3weeks/3%EC%A3%BC%EC%B0%A8

**Comment by dbswl067** [comment]
3주차 완료
url: https://github.com/dbswl067/2021-java-a/tree/main/3%EC%A3%BC%EC%B0%A8%20%EA%B3%BC%EC%A0%9C
