### ISSUE TITLE
4주차: 자바코드 작성해보기 

### ISSUE THREAD

**Issue by Livenow14** [Learning-Now/2021-Java-Study#24]
### **정리할 것**

- 역할, 책임, 협력(객체지향의 사실과 오해) → 제일 중요한것은 메세지다
- vo(value object)

### 실습

- 문자열 계산기 ( 프로그래밍과제 1 )

---

### **목표**

자바가 제공하는 다양한 연산자를 학습하세요.

### **학습할 것**

- 산술 연산자
- 비트 연산자
- 관계 연산자
- 논리 연산자
- instanceof
- assignment(=) operator
- 화살표(->) 연산자
- 3항 연산자
- 연산자 우선 순위
- (optional) Java 13. switch 연산자

## **제출 양식**

- pr 예시: **[3주차] 이니셜 제출**
- 이슈 예시:

```java
3주차 완료
url: ~~
```

**Comment by BLINK-ONCE** [comment]
4주차 완료
url: https://github.com/BLINK-ONCE/2021-Java-Study/tree/4weeks/4weeks

**Comment by DongLee99** [comment]
4주차 완료
url : https://velog.io/@donglee99/4주차-과제-자바-코드-작성해보기

**Comment by jeongyuneo** [comment]
4주차 완료
url: https://github.com/jeongyuneo/2021-Java-Study/tree/4주차

**Comment by dbswl067** [comment]
4주차 완료
url: https://github.com/dbswl067/2021-java-a/tree/main/4%EC%A3%BC%EC%B0%A8%20%EA%B3%BC%EC%A0%9C

**Comment by dustndus8** [comment]
4주차 완료
url: https://github.com/dustndus8/2021-Java-Study-1.git
