### ISSUE TITLE
5주차: 자바 익숙해지기

### ISSUE THREAD

**Issue by Livenow14** [Learning-Now/2021-Java-Study#26]
### **정리할 것**

- 문자열 계산기에서 객체 책임 정리
- 구현할 기능 목록 정리

### 실습

- 문자열 계산기 리팩토링 ( 프로그래밍과제 1 )

---

### **목표**

자바가 제공하는 제어문을 학습하세요.

### **학습할 것 (필수)**

- 선택문
- 반복문

# **과제 (옵션)**

## **과제 0. JUnit 5 학습하세요.**

- 인텔리J, 이클립스, VS Code에서 JUnit 5로 테스트 코드 작성하는 방법에 익숙해 질 것.
- 이미 JUnit 알고 계신분들은 다른 것 아무거나!
- [더 자바, 테스트](https://www.inflearn.com/course/the-java-application-test?inst=86d1fbb8) 강의도 있으니 참고하세요~

## **과제 1. live-study 대시 보드를 만드는 코드를 작성하세요.**

- 깃헙 이슈 1번부터 5번까지 댓글을 순회하며 댓글을 남긴 사용자를 체크 할 것.
- 참여율을 계산하세요. 총 5회에 중에 몇 %를 참여했는지 소숫점 두자리가지 보여줄 것.
- [Github 자바 라이브러리](https://github-api.kohsuke.org/)를 사용하면 편리합니다.
- 깃헙 API를 익명으로 호출하는데 제한이 있기 때문에 본인의 깃헙 프로젝트에 이슈를 만들고 테스트를 하시면 더 자주 테스트할 수 있습니다.

## **과제 2. LinkedList를 구현하세요.**

- LinkedList에 대해 공부하세요.
- 정수를 저장하는 ListNode 클래스를 구현하세요.
- ListNode add(ListNode head, ListNode nodeToAdd, int position)를 구현하세요.
- ListNode remove(ListNode head, int positionToRemove)를 구현하세요.
- boolean contains(ListNode head, ListNode nodeTocheck)를 구현하세요.

## **과제 3. Stack을 구현하세요.**

- int 배열을 사용해서 정수를 저장하는 Stack을 구현하세요.
- void push(int data)를 구현하세요.
- int pop()을 구현하세요.

## **과제 4. 앞서 만든 ListNode를 사용해서 Stack을 구현하세요.**

- ListNode head를 가지고 있는 ListNodeStack 클래스를 구현하세요.
- void push(int data)를 구현하세요.
- int pop()을 구현하세요.

## **과제 5. Queue를 구현하세요.**

- 배열을 사용해서 한번
- ListNode를 사용해서 한번.

## 주의 사항 (소프트웨어 의식적 연습 - 객체지향 생활 체조 원칙)
```
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.
규칙 2: else 예약어를 쓰지 않는다.
규칙 3: 모든 원시값과 문자열을 포장한다.
규칙 4: 한 줄에 점을 하나만 찍는다.
규칙 5: 줄여쓰지 않는다(축약 금지).
규칙 6: 모든 엔티티를 작게 유지한다.
규칙 7: 2개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.
규칙 8: 일급 콜렉션을 쓴다.
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.
```

## **제출 양식**

- pr 예시: **[3주차] 이니셜 제출**
- 이슈 예시:

```java
3주차 완료
url: ~~
```

**Comment by Livenow14** [comment]
메시지는 '어떻게' 수행될지는 명시하지 않음, 단지 오퍼레이션을 통해 '무엇'이 실행되기를 바라는지만 명시

- ex) 예매하라

어떤 메서드를 선택할 것인지는 전적으로 수신자의 결정에 좌우 

메시지를 수신한 객체가 실행 시간에 메서드를 선택할 수 있다는 사실은 절차지향 언어와 객체지향 프로그래밍을 구분 짓는 핵심적인 특징 중 하나임. → 다형성(하나의 메시지와 하나 이상의 메서드 사이와 관계)이라고 부름 

다형성은 수신자의 종류를 캡슐화 한다 ( 객체들의 대체 가능성의 특성을 이용, 메시지 송진자가 수신자의 종류를 모르더라도 메시지를 전송할수 있다. )

## .ignore파일 예시
```java
# Created by .ignore support plugin (hsz.mobi)
.DS_Store
**/.DS_Store

.gradle
/build/
!gradle/wrapper/gradle-wrapper.jar
/out/
/target/

### STS ###
.apt_generated
.classpath
.factorypath
.project
.settings
.springBeans
bin/

### IntelliJ IDEA ###
.idea
*.iws
*.iml
*.ipr

# IntelliJ project files
out
gen

```

**Comment by jeongyuneo** [comment]
5주차 완료
url: https://github.com/jeongyuneo/2021-Java-Study/tree/5주차

**Comment by dustndus8** [comment]
5주차 완료
url: https://github.com/dustndus8/2021-Java-Study-1.git

**Comment by BLINK-ONCE** [comment]
5주차 완료
url: https://github.com/BLINK-ONCE/2021-Java-Study/tree/5weeks/5weeks

**Comment by DongLee99** [comment]
5주차 완료 
url: https://github.com/DongLee99/2021-Java-Study/tree/5week
