### ISSUE TITLE
6주차: 클래스, enum 이란?

### ISSUE THREAD

**Issue by Livenow14** [Learning-Now/2021-Java-Study#38]
### 객체 지향 생활 체조 원칙에 맞는 문자열 계산기 구현

---

## **목표**

자바의 Class에 대해 학습하세요.

## **학습할 것**

- 클래스 정의하는 방법
- 객체 만드는 방법 (new 키워드 이해하기)
- 메소드 정의하는 방법
- 생성자 정의하는 방법
- this 키워드 이해하기

## **제출 양식**

- pr 예시: **[3주차] 이니셜 제출**
- 이슈 예시:

```java
3주차 완료
url: ~~
```

## **주의 사항 (소프트웨어 의식적 연습 - 객체지향 생활 체조 원칙)**

```
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.
규칙 2: else 예약어를 쓰지 않는다.
규칙 3: 모든 원시값과 문자열을 포장한다.
규칙 4: 한 줄에 점을 하나만 찍는다.
규칙 5: 줄여쓰지 않는다(축약 금지).
규칙 6: 모든 엔티티를 작게 유지한다.
규칙 7: 2개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.
규칙 8: 일급 콜렉션을 쓴다.
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.
규칙 10: 한 메서드에 10줄 이상 사용하지 않는다.
```

### 3. 발표

enum의 개념 및 사용법

**Comment by jeongyuneo** [comment]
6주차 완료
url: https://github.com/jeongyuneo/2021-Java-Study/tree/6주차

**Comment by DongLee99** [comment]
6주차 완료
url : https://github.com/DongLee99/2021-Java-Study/tree/6week

**Comment by dbswl067** [comment]
6주차 완료
url: https://github.com/dbswl067/2021-Java-Study/tree/6weeks

**Comment by dustndus8** [comment]
6주차 완료
url: https://github.com/dustndus8/2021-Java-Study-1/tree/hw6

**Comment by BLINK-ONCE** [comment]
6주차 완료
url: https://github.com/BLINK-ONCE/2021-Java-Study/tree/6weeks
