### ISSUE TITLE
7주차: 상속, enum 심화 

### ISSUE THREAD

**Issue by Livenow14** [Learning-Now/2021-Java-Study#44]
## **목표**

자바의 상속에 대해 학습하세요.

## **학습할 것 (필수)**

- 자바 상속의 특징
- super 키워드
- 메소드 오버라이딩
- 다이나믹 메소드 디스패치 (Dynamic Method Dispatch)
    - 더블 디스패치
- 추상 클래스
- final 키워드
- Object 클래스

**Comment by Livenow14** [comment]
### 자바 문자열

### 문자와 문자열

### 상속

### 업캐스팅(upcasting) vs 다운캐스팅(downcasting)

### 인터페이스(interface)

**Comment by DongLee99** [comment]
7주차 완료
url : https://github.com/DongLee99/2021-Java-Study/tree/7week

**Comment by dbswl067** [comment]
7주차 완료
url: https://github.com/dbswl067/2021-Java-Study/tree/7weeks

**Comment by BLINK-ONCE** [comment]
7주차 완료
url: https://github.com/BLINK-ONCE/2021-Java-Study/tree/7weeks

**Comment by jeongyuneo** [comment]
7주차 완료
url: https://github.com/jeongyuneo/2021-Java-Study/tree/7주차
