### ISSUE TITLE
2주차 과제: Java 코드 돌려보기 

### ISSUE THREAD

**Issue by Livenow14** [Learning-Now/2021-Java-Study#7]
### 정리할 것

- java 11 jdk 다운받고 실행해보기
- 단축키 정리
- Live template 정리

---

## 2. 자바 기초

JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가.

### 목표

자바 소스 파일(.java)을 JVM으로 실행하는 과정 이해하기

### 정리할 것

- JVM이란 무엇인가
- 컴파일 하는 방법
- 실행하는 방법
- 바이트코드란 무엇인가
- JIT 컴파일러란 무엇이며 어떻게 동작하는지
- JVM 구성 요소
- JDK와 JRE의 차이

## 제출 양식

- pr 예시: **[2주차] 이니셜 제출**
- 이슈 예시:

```java
2주차 완료
url: ~~  
```

## 참고 자료

- [코드 컨벤션](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
    - [내가 정리한 것](https://velog.io/@livenow/Java-Code-Convention)

**Comment by jeongyuneo** [comment]
2주차 완료
url: https://github.com/jeongyuneo/2021-Java-Study/tree/jeongyun

**Comment by dustndus8** [comment]
2주차 완료
url: https://github.com/dustndus8/2021-Java-Study-1.git

**Comment by DongLee99** [comment]
2주차 완료
ulr : https://velog.io/@donglee99/2주차-과제-JAVA-코드-둘러보기

**Comment by BLINK-ONCE** [comment]
2주차 완료
url: https://github.com/BLINK-ONCE/2021-java-study-HW/tree/main/2%EC%A3%BC%EC%B0%A8

**Comment by dbswl067** [comment]
2주차 완료
url: https://github.com/dbswl067/2021-java-a/tree/main/2%EC%A3%BC%EC%B0%A8%20%EA%B3%BC%EC%A0%9C
